My pull request: Microverse.
BerkcanCakar/Hello_Microverse pull request #1
Opened 2022-01-04 15:02 UTC by BerkcanCakar

merge to main

2022-01-04 15:09 UTC, rotimiazeez requested changes
# Hi @BerkcanCakar 👋, 
## Good job so far!👍
### There are some issues that you still need to work on to go to the next project but you are almost there!😉
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly make sure your page check for linters and all should pass

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-05 17:16 UTC, medaminedev66 reviewed
Hi @BerkcanCakar, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight
- ✔️Git/GitHub flow best practices have been followed
- ✔️There are no linter errors

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-05 17:16 UTC, medaminedev66 commented on test.md
> +this file should be ignored by git.
To maintain our git history clean, let's make sure to add `test.md` file to the [.gitignore](https://stackoverflow.com/questions/13675216/why-should-i-use-gitignore) file. What do you think? The purpose of gitignore files is to ensure that certain files not tracked by git remain untracked.

2022-01-05 22:31 UTC, enkog approved these changes
Hi @BerkcanCakar 👋, 

Good job implementing the required changes from the previous reviewer.

## Highlight
✅ Linters are set up correctly and they pass.
✅ README is descriptive.

### Status: APPROVED ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

![image](https://user-images.githubusercontent.com/81468675/147213535-ab80a883-5bf8-4284-b9ee-d90332328671.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-05 22:31 UTC, enkog commented on README.md
> +![screenshot](./app_screenshot.png)
- [OPTIONAL] Please fix this broken link. You can add an actual screenshot.png image to your project directory and then reference it appropriately or add this `https://user-images.githubusercontent.com/26796167/148297322-2bfd6422-71fa-4ec4-bac0-030eec6af2e4.PNG` instead of the `./app_screenshot.png`. This will enable visitors of this repository to see the actual outcome of the page.

2022-01-06 07:31 UTC, merged